#rename this file to config.ini #todo: anonimise
[Evohome]
Username = robinvankappel@gmail.com
Password = 6tGxoBS9#rxM5J7p

#same roomnames on Evohome system (login at https://international.mytotalconnectcomfort.com/Locations), then retrieve via Inspector
#It is not required in this script
#[Rooms]

